<Project>
	<!-- Directory.Build.targets 
	
	See Readme.md for prerequisites.
	
	-->
	

	<!-- AssemblySearchPaths and AcReferencePath are assigned
	multiple times, once for each build cycle that targets a 
	different framework version. This ensures that MSBUILD finds 
	the correct	reference assemblies for each target framework.-->
	
	<PropertyGroup Condition="Exists('$(AcReferencePath)')">
		<AssemblySearchPaths>$(AcReferencePath);$(AssemblySearchPaths)</AssemblySearchPaths>
	</PropertyGroup>

	<!-- 
	========================================================= 
	Predefined references for basic AutoCAD assemblies to be
	used by all projects that use this file. 
	
	Because AssemblySearchPaths is set to the path to AutoCAD
	assembly references for each targeted framework, Visual
	Studio will NOT use a <HintPath/> element if present, and
	instead looks for the referenced assembly in the location 
	that was specified for the current target framework by the
	build logic in Directory.Build.props. For that reason, a 
	best practice is to not include a <HintPath/> element in 
	AutoCAD assembly references both in this file, and in any
	.csproj files that use this file.
	
	You can add additional references here, keeping in mind 
	that they will be used by all projects that use this file.
	
	To accomodate extensions that are designed to not have a
	dependence on AutoCAD (e.g., loaded into AcCoreConsole.exe,
	or another RealDwg host application), You can set the
	<RealDwgExtension> property to true in your .csproj file. 
	If you do that, AcMgd.dll is not referenced.
	
	========================================================= 
	-->

	<ItemGroup>
		<Reference Include="acmgd"
				   Condition="'$(RealDwgExtension)' != 'true'"> 
			<Private>false</Private> 
		</Reference>
		<Reference Include="acdbmgd"> <Private>false</Private> </Reference>
		<Reference Include="accoremgd"> <Private>false</Private> </Reference>
	</ItemGroup>

	<!-- Diagnostics / Informational output -->
	
	<!-- Format the target framework and AutoCAD release display name -->
	<PropertyGroup>
		<TargetDisplayName>AutoCAD $(AcMinVer) / .NET $(TargetFrameworkVersion)</TargetDisplayName>
	</PropertyGroup>

	<!-- Pre-build: display the build target display 
	name and the path to the AutoCAD reference assemblies 
	that are to be used for the build target.-->

	<Target Name="BeginBuildMessage" BeforeTargets="ResolveAssemblyReferences">
		<Message Text="[$(MSBuildProjectName)]: Building target for $(TargetDisplayName) using references from $(AcReferencePath)"
			Condition="'$(AcReferencePath)' != ''"
			Importance="high"></Message>
	</Target>

	<!-- Post-build: display the build target display 
	name and the path to the AutoCAD reference assemblies 
	that were used used for the build target.-->
	
	<Target Name="AfterBuildMessage" AfterTargets="Build">
		<Message Text="[$(MSBuildProjectName)]: Built target for $(TargetDisplayName) using references from $(AcReferencePath)"
			Condition="'$(AcReferencePath)' != ''"
			Importance="high"></Message>
	</Target>

	<!-- Check that required environment variables are defined for 
		 each target framework, and point to a valid path:
	-->

	<Target Name="ValidateAcRefPath" BeforeTargets="PrepareForBuild">
		<Error Condition=" '$(_Ver)' == '4' And ( '$(AC_NET_4_REF_PATH)' == '' Or !Exists('$(AC_NET_4_REF_PATH)') ) "
			Text="[$(MSBuildProjectName)]:  The 'AC_NET_4_REF_PATH' environment variable is not set or contains an invalid path for the target framework '$(TargetFramework)'. Current Value: '$(AC_NET_4_REF_PATH)'. Please define the 'AC_NET_4_REF_PATH' environment variable to point to the location of AutoCAD 2020-2024 reference assemblies."/>

		<Error Condition=" '$(_Ver)' == '8' And ( '$(AC_NET_8_REF_PATH)' == '' Or !Exists('$(AC_NET_8_REF_PATH)') ) "
			Text="[$(MSBuildProjectName)]:  The 'AC_NET_8_REF_PATH' environment variable is not set or contains an invalid path for the target framework '$(TargetFramework)'. Current Value: '$(AC_NET_8_REF_PATH)'. Please define the 'AC_NET_8_REF_PATH' environment variable to point to the location of AutoCAD 2025-2026 reference assemblies."/>

		<Error Condition=" '$(_Ver)' == '10' And ( '$(AC_NET_10_REF_PATH)' == '' Or !Exists('$(AC_NET_10_REF_PATH)') ) "
			Text="[$(MSBuildProjectName)]: The 'AC_NET_10_REF_PATH' environment variable is not set or contains an invalid path for the target framework '$(TargetFramework)'. Current Value: '$(AC_NET_10_REF_PATH)'. Please define the 'AC_NET_10_REF_PATH' environment variable to point to the location of AutoCAD 2027 reference assemblies."/>
	</Target>

	<!-- Displays the assembly search path for debug/diagnostics purposes 
	To enable, use <DebugAssemblySearchPaths>true</DebugAssemblySearchPaths>
	in the .csproj file.
	-->
	<Target Name="DebugAssemblySearchPaths" 
			Condition="'$(DebugAssemblySearchPaths)' == 'true'"
			BeforeTargets="ResolveAssemblyReferences">
		<Message Text="[$(MSBuildProjectName)]: AssemblySearchPaths: $(AssemblySearchPaths)" Importance="high" />
	</Target>

</Project>

