<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0;net471</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<!-- Example of a project-specific reference
	to an AutoCAD assembly. This reference was added
	using the Visual Studio UI, which generated a
	<HintPath/> element referencing the AutoCAD 2025
	version of acdbmgdbrep.dll, which cannot be used
	with other targeted frameworks.
	
	To solve this problem in a transparent way, the 
	build logic in the included Directory.Build.*
	files tells MSBUILD to use the paths they provide
	for each target framework, and to ignore the value
	provided in the <HintPath/> element.
	
	You can remove the <HintPath/> element below to
	confirm that the correct version of acdbmgdbrep.dll
	is used with each targeted framework.
	
	-->
	
	<ItemGroup>
		<Reference Include="acdbmgdbrep">
			<HintPath>..\..\..\..\..\..\Program Files\Autodesk\AutoCAD 2025\acdbmgdbrep.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
